/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbs;
import Service.Phieumuasach;
import Service.Controller;
import Service.Nhanvien;
import Utils.DateUtils;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FormPhieuMuaSach extends javax.swing.JFrame {

    /**
     * Creates new form FormThanhToanNhapSach
     */
    Controller<Phieumuasach> ketNoi_PMS = new Controller<>(Phieumuasach.class);
    Controller<Nhanvien> ketNoi_NV = new Controller<>(Nhanvien.class);
    DefaultTableModel model;
    
    public FormPhieuMuaSach() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        List<Nhanvien> nhanVienList = ketNoi_NV.getAll();
        
        // Xóa toàn bộ mục hiện tại trong ComboBox
        cboMaNV.removeAllItems();
        
        // Thêm mục cho từng nhân viên vào ComboBox
        for (Nhanvien nv : nhanVienList) {
            cboMaNV.addItem(nv.getMaNV() + " - " + nv.getTenNV());
        }
        
        loadData();
    }
    
    void loadData () {
        ketNoi_PMS.loaddata(model, new String[] {"getSoPhieu", "getNgay", 
            "getTenNCC", "getInforNhanVien", "getThanhToan"});
    }
    
    void clear() {
        ketNoi_PMS.clear(new JTextField[] {txtSoPhieu, txtTenNCC}, model);
        cboMaNV.setSelectedIndex(-1);
        DateUtils.setDateToCurrent(dtpNgayGiaoDich);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoPhieu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboMaNV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dtpNgayGiaoDich = new com.toedter.calendar.JDateChooser();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnChiTietPhieu = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU MUA SÁCH");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Số phiếu");

        txtSoPhieu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSoPhieu.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Tên nhà cung cấp");

        txtTenNCC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Mã nhân viên");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Ngày giao dịch");

        dtpNgayGiaoDich.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phiếu", "Ngày giao dịch", "Tên nhà cung cấp", "Mã nhân viên", "Thanh toán"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnChiTietPhieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChiTietPhieu.setText("Chi tiết phiếu");
        btnChiTietPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietPhieuActionPerformed(evt);
            }
        });

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThanhToan.setText("Thanh toán");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 105, Short.MAX_VALUE)
                        .addComponent(btnThem)
                        .addGap(32, 32, 32)
                        .addComponent(btnSua)
                        .addGap(28, 28, 28)
                        .addComponent(btnXoa)
                        .addGap(37, 37, 37)
                        .addComponent(btnClear)
                        .addGap(59, 59, 59)
                        .addComponent(btnChiTietPhieu)
                        .addGap(38, 38, 38)
                        .addComponent(btnThanhToan)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoPhieu)
                            .addComponent(dtpNgayGiaoDich, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboMaNV, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtTenNCC))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dtpNgayGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cboMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnClear)
                    .addComponent(btnChiTietPhieu)
                    .addComponent(btnThanhToan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        Phieumuasach pms = new Phieumuasach();
        
        pms.setNgay(dtpNgayGiaoDich.getDate());
        pms.setTenNCC(txtTenNCC.getText());
        
        Object selectedMaNV = cboMaNV.getSelectedItem();
        if (selectedMaNV != null) {
            String selectedValue = selectedMaNV.toString();
            String[] parts = selectedValue.split(" - ");
            if (parts.length >= 1) {
                try {
                    int maNV = Integer.parseInt(parts[0]);
                    Nhanvien nhanVien = new Nhanvien(maNV); // Tạo một đối tượng Nhanvien mới với maNV
                    pms.setMaNV(nhanVien);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return; // Dừng lại nếu có lỗi
                }
            } else {
                JOptionPane.showMessageDialog(this, "Dữ liệu nhân viên không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; // Dừng lại nếu không có mã nhân viên hợp lệ được chọn
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã nhân viên.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return; // Dừng lại nếu không có mã nhân viên được chọn
        }
        
        pms.setThanhToan(false);
        
        ketNoi_PMS.addSv(pms);
        clear();
        loadData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row >= 0 ) {
            int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            txtSoPhieu.setText(String.valueOf(id));
            
            Date ngayGiaoDich = DateUtils.parseDate(jTable1.getValueAt(row, 1).toString());
            dtpNgayGiaoDich.setDate(ngayGiaoDich);
            
            txtTenNCC.setText(jTable1.getValueAt(row, 2).toString());
            
            //int maNV = Integer.parseInt(jTable1.getValueAt(row, 3).toString());
            cboMaNV.setSelectedItem(jTable1.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtSoPhieu.getText() != null) {
            Phieumuasach pms = new Phieumuasach();
            pms.setSoPhieu(Integer.parseInt(txtSoPhieu.getText()));
            pms.setNgay(dtpNgayGiaoDich.getDate());
            pms.setTenNCC(txtTenNCC.getText());
            
            Object selectedMaNV = cboMaNV.getSelectedItem();
            if (selectedMaNV != null) {
                String selectedValue = selectedMaNV.toString();
                String[] parts = selectedValue.split(" - ");
                if (parts.length >= 1) {
                    try {
                        int maNV = Integer.parseInt(parts[0]);
                        Nhanvien nhanVien = new Nhanvien(maNV); // Tạo một đối tượng Nhanvien mới với maNV
                        pms.setMaNV(nhanVien);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Mã nhân viên không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        return; // Dừng lại nếu có lỗi
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Dữ liệu nhân viên không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return; // Dừng lại nếu không có mã nhân viên hợp lệ được chọn
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn mã nhân viên.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; // Dừng lại nếu không có mã nhân viên được chọn
            }
            
            boolean thanhToan = (boolean) jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getColumnCount() - 1);
            pms.setThanhToan(thanhToan);
            
            ketNoi_PMS.sua(pms);
            clear();
            loadData();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtSoPhieu.getText() != null) {
            ketNoi_PMS.xoa(txtSoPhieu.getText());
            clear();
            loadData();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
        loadData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnChiTietPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietPhieuActionPerformed
        
    }//GEN-LAST:event_btnChiTietPhieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPhieuMuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPhieuMuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPhieuMuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPhieuMuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPhieuMuaSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTietPhieu;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaNV;
    private com.toedter.calendar.JDateChooser dtpNgayGiaoDich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSoPhieu;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
